package:
  name: clickhouse-24.12-bitnami-compat
  version: "25.2.1.3085"
  epoch: 0
  description: Clickhouse 
  copyright:
    - license: Apache-2.0
  resources:
    cpu: 65
    memory: 32Gi

environment:
  contents:
    packages:
      - clickhouse-25.1-bitnami-compat

pipeline:
  - uses: bitnami/compat
    with: 
      image: clickhouse
      version-path: 25/debian-12
    runs: |
      install -Dm755 ../docker/server/entrypoint.sh ${{targets.destdir}}/entrypoint.sh
      mkdir -p ${{targets.destdir}}/etc/clickhouse-server/config.d/
      cp  ../docker/server/docker_related_config.xml ${{targets.destdir}}/etc/clickhouse-server/config.d/docker_related_config.xml