package:
  name: llvm-libcxx-19
  version: 19.1.7
  epoch: 1
  description: The LLVM libc++ libraries
  copyright:
    - license: Apache-2.0
  dependencies:
    provides:
      - llvm-libcxx=19

environment:
  contents:
    packages:
      - autoconf
      - automake
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang
      - cmake
      - curl
      - git
      - python3
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/llvm/llvm-project
      tag: llvmorg-${{package.version}}
      expected-commit: cd708029e0b2869e80abe31ddb175f7c35361f90

  - runs: |
      cmake -G Ninja -S runtimes -B build \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++ \
        -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \ # LIBCXXABI_USE_LLVM_UNWINDER requires libunwind
        -DLLVM_INCLUDE_TESTS=OFF \
        -DLIBCXX_INCLUDE_BENCHMARKS=OFF

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR=${{targets.destdir}} cmake --install build

  - uses: strip

subpackages:
  - name: llvm-libcxx-19-dev
    pipeline:
      - uses: split/dev
    dependencies:
      provides:
        - llvm-libcxx-dev=19

  - name: llvm-libcxxabi-19
    pipeline:
      - runs: |
          mkdir -p ${{targets.subpkgdir}}/usr/lib
          mv ${{targets.destdir}}/usr/lib/libc++abi.so* ${{targets.subpkgdir}}/usr/lib/
    test:
      pipeline:
        - uses: test/ldd-check
          with:
            packages: $(basename ${{targets.contextdir}})
    dependencies:
      provides:
        - llvm-libcxxabi=19

update:
  enabled: true
  github:
    identifier: llvm/llvm-project
    use-tag: true
    tag-filter: llvmorg-19.
    strip-prefix: llvmorg-

test:
  pipeline:
    - uses: test/ldd-check
      with:
        packages: ${{package.name}}
