package:
  name: lua-resty-events
  version: 0.3.1
  epoch: 0
  description: "Inter process Pub/Sub pattern for Nginx worker processes"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/Kong/lua-resty-events
      tag: ${{package.version}}
      expected-commit: bc85295b7c23eda2dbf2b4acec35c93f77b26787

  - uses: autoconf/make

  - uses: autoconf/make-install

update:
  enabled: true
  github:
    identifier: openresty/lua-resty-events
    use-tag: true

test:
  pipeline:
    - uses: test/tw/ldd-check
